apiVersion: v1
kind: Service
metadata:
  name: doss-iam-api
  labels:
    app: doss-iam-api
spec:
  ports:
    - name: http #http로
      port: 9090 #80으로 편함
      targetPort: 9090
#    - name: https #http로
#      port: 443 #80으로 편함
#      targetPort: 9090
  selector:
    app: doss-iam-api
  type: LoadBalancer