server:
  port: 9090

spring:
  application:
    name: doss-iam-api
  profiles:
    active: local

mybatis:
  type-aliases-package: com.skt.doss.portal
  mapper-locations: db/*.xml
  configuration: 
    map-underscore-to-camel-case: true